using RapGame.Models;
using System;
using System.Collections.Generic;

namespace ElectronRazorPage
{
    public static class Texts
    {
        public static List<TextModel> TextsForFrames = new List<TextModel>()
        {
            new TextModel { FrameNumber = 4, Text = "<div class=\"display-1\"><b>Hi there! My name is <br> Proph and I am here to <br> teach you how to rap!</b></div>"},
            new TextModel { FrameNumber = 7, Text = "<div class=\"display-2\"><b>But you need to watch out <br> for The Mic Menace <br> because he is evil and likes <br> to steal microphones!</b></div>"},
            new TextModel { FrameNumber = 8, Text = "<div class=\"display-1\"><b>Oh no, here comes The <br>  Mic Menace. I better <br> make a run for it!</b></div>"},
            new TextModel { FrameNumber = 10, Text = "<div class=\"display-1 text-center\"><b>Phew, that was close! <br> Sorry I had to jet. The Mic <br> Menace is way too scary!</b></div> <div class=\"display-1 pt-5 animate__animated animate__fadeIn animate__delay-2s\" style=\"text-align:center\"><b>Where was I…</b></div>"},
            new TextModel { FrameNumber = 11, Text = "<div class=\"col-10 offset-1 ps-5\"> <div class=\"display-2 pb-5 ps-5 ms-1 z-67\"><b>Throughout the game, you are going <br> to see the below after specific <br> games:</b></div></div>"},
            new TextModel { FrameNumber = 12, Text = "<div style=\"text-align:center\" class=\"display-5\"><b>1 is the lowest on the scale and 10 is the <br> highest.</b></div> <div style=\"text-align:center\" class=\"display-5 pt-5\"><b><b>Example</b>: If you are sad, you might put a 1 <br>but if you are happy you might put a 10.</b></div> <div style=\"text-align:center\" class=\"pt-3 display-5 pt-5 pb-5\"><b>It is important that you are totally honest!</b></div>"},
            new TextModel { FrameNumber = 13, Text = "<div class=\"display-2 z-90\" style=\"text-align:center \"><b>Let’s give it a try!</b></div> <div class=\"display-2 pt-5 pb-5 z-90\" style=\"text-align:center\"><b>Slide the cursor to the number that <br> best matches how you are feeling.</b></div>"},
            new TextModel { FrameNumber = 14, Text = "<div class=\"display-4\"><b>Along the way, there may be <br> some words that you might need <br> the definition of, all you need to   <br> do is click on the <text style=\"color: rgb(1,1,225)\">blue</text> word for <br> the definition and an example!</b></div>"},
            new TextModel { FrameNumber = 15, Text = "<div style=\"text-align:center\" class=\"display-3 pb-4\"><b>A rap needs to <br><div><a style=\"font-size:4.7rem\" id=\"end\" href=\"Frame4Template?FrameNumber=16\">rhyme</a></div> so we are going to start with a game!</b></div> <div class=\"display-3 pt-5\" style=\"text-align:center\"><b id=\"start\">Click the following <br>word to move on.</b></div>"},
            new TextModel { FrameNumber = 16, Text = "<div style=\"color:#0000FF; text-align:center; padding-right:10rem\" class=\"position-center display-2 pb-5\"><b>Rhyme</b></div> <div class=\"display-5\"><b>A rhyme is where two words (especially <br>the ending of the word) sounds similar to <br> each other.</b></div> <div class=\"display-5 pt-5\"><b><b>For example:</b> ‘c<u>ar</u>’ and ‘f<u>ar</u>’ rhyme with each <br> other because the endings of both make <br> the same ‘ar’ sound.</b></div>"},
            new TextModel { FrameNumber = 21, Text = "<div style=\"color:#0000FF; padding-left: 12rem\" class=\"display-1 animate__animated animate__zoomIn animate__slow\"><b>Obtain</b></div> <div class=\"display-5 pt-5 animate__animated animate__fadeInUp animate__delay-2s\"><b>Obtain means to get or secure <br> something.</b></div> <div class=\"display-5 pt-5 animate__animated animate__fadeInUp animate__delay-3s\"><b><b>For example</b></b><b>: the human being had to <br> obtain Mystical Mic to move forward in <br> the game.</b></div>"},
            new TextModelFrame25{ FrameNumber = 25, Header = "<div class=\"col-xl-3 offset-xl-3 display-4 animate__animated animate__fadeInUp animate__slower z-110 \"><b>Hey there…</b></div>"  ,Text = "<div class=\"col-8\"><div class=\"row mb-5\"><div class=\"col-6 align-self-start text-start pb-2 pe-5 animate__animated animate__fadeInUp animate__delay-1s  animate__slower z-110\"><div class=\"display-3 \"><b>My name is Rhyming<br>Rebecca and I’m here<br>to teach you about<br><a href='Frame26' class=\"z-100\">rhyme schemes.</a></b></div></div></div><div class=\"row\"><div class=\"offset-4 col-6 align-self-end text-start pb-2 pe-5 animate__animated animate__fadeInUp animate__delay-4   s animate__slower z-110 ps-5\"><div class=\"display-3 \"><b>There are loads of<br>rhyme schemes, but<br>on our journey, we<br>only need to be<br>aware of three!</b></div></div></div></div>" },
            new TextModelFrame25{ FrameNumber = 27, Header = "<div class=\"text-center display-1 text-success z-110 pe-5\"> <b>AAAA</b></div>", Text = "<div class=\"col-8 z-140\"> <div class=\"row\"><div class=\"col-5 align-self-start text-start pt-2 pl-3 animate__animated animate__fadeInUp animate__slower animate__delay-2s pb-4\"><div class=\"display-4 \"><b class=\"text-success\">AAAA </b><b> is the first<br>rhyme scheme. </b></div></div></div><div class=\"row\"><div class=\"offset-3 pe-5 col-5 align-self-center text-start animate__animated animate__fadeInUp animate__delay-4s animate__slower\"><div class=\"display-4 \"><b>This is where<br>all of the last<br>words rhyme<br>with each other.</b></div></div></div><div class=\"row\"><div class=\"offset-7 col-4 align-self-end text-start animate__animated animate__fadeInUp animate__delay-6s animate__slower\"><div class=\"display-4 \"><b>Let’s look at an<br>example on the<br>next page.</b></div></div></div>" },
            new TextModelFrame25{ FrameNumber = 36, Header = "<div class=\"text-center display-1 text-success\">  <b class=\"text-success\">AA</b><b  style=\"color:#8B008B\">BB </b></div>", Text = "<div class=\"col-8\"> <div class=\"row\"><div class=\"col-5 align-self-start text-start pt-2 pl-3 z-140 animate__animated animate__fadeInUp animate__slower animate__delay-2s\"><div class=\"display-4 \"><b class=\"text-success\">AA</b><b  style=\"color:#8B008B\">BB </b><b>  is the second<br>rhyme scheme.</b></div></div></div><br><div class=\"row pt-5\"><div class=\"offset-2 col-8 align-self-center text-start animate__animated animate__fadeInUp animate__slower animate__delay-4s z-130\"><div class=\"display-5 \"><b>This is where the first two lines<br>rhyme with each other and the<br>last two lines rhyme with each<br>other. Lines 1 and 2 do not<br>rhyme with lines 3 and 4. </b></div></div></div><br><div class=\"row pt-5\"><div class=\"offset-6 col-4 align-self-end text-start animate__animated animate__fadeInUp animate__slower animate__delay-6s z-140 \"><div class=\"display-4 \"><b>Let’s look at an<br>example on the<br>next page.</b></div></div></div>" },
            new TextModel {FrameNumber = 34, Text = "Well done, you have now learnt the rhyme scheme <label class=\"text-success\">AAAA</label>"},
            new TextModel {FrameNumber = 43, Text = "Well done, you have now learnt the rhyme scheme <br><label class=\"text-success\">AA</label><label style=\"color:#8B008B\">BB</label>"},
            new TextModelFrame25{ FrameNumber = 45, Header = "<div class=\"text-center display-1 text-success\"> <b class=\"text-success\">A</b><b style=\"color:#8B008B\">B</b><b class=\"text-success\">A</b><b style=\"color:#8B008B\">B</b></div>", Text = "<div class=\"col-8\"> <div class=\"row\"><div class=\"col-4 align-self-start text-start pt-2 pl-3 z-140 animate__animated animate__fadeInUp animate__slower animate__delay-2s\"><div class=\"display-4 \"><b class=\"text-success\">A</b><b style=\"color:#8B008B\">B</b><b class=\"text-success\">A</b><b style=\"color:#8B008B\">B</b><b>  is the third<br>rhyme scheme.</b></div></div></div><div class=\"row mt-5\"><div class=\"offset-3 col-8 align-self-center text-start z-130 animate__animated animate__fadeInUp animate__slower animate__delay-4s\"><div class=\"display-5 z-110\"><b>This is where the first line<br>rhymes with the third line<br>and the second line rhymes<br>with the fourth line.</b></div></div></div><div class=\"row mt-5\"><div class=\"offset-8 col-4 align-self-end text-start z-140 animate__animated animate__fadeInUp animate__slower animate__delay-6s\"><div class=\"display-4 \"><b>Let’s look at an<br>example on the<br>next page.</b></div></div></div>" },
            new TextModel {FrameNumber = 52, Text = "Well done, you have now learnt the rhyme scheme<br> <label class=\"text-success\">A</label><label style=\"color:#8B008B\">B</label><label class=\"text-success\">A</label><label style=\"color:#8B008B\">B</label>"},
            new TextModel { FrameNumber = 61, Text = "Well done!"},
            new TextModel {FrameNumber = 107, Text = "<div class=\"display-2\"><b style=\"color:#0000FF;\">Internal rhyme</b></div> <div class=\"display-5 pt-5\"><b>An internal rhyme is <br /> where two or more words rhyme in the same line.</b></div> <div class=\"display-5 pt-5\"><b>Say the definition out loud.</b></div><div class=\"display-5 pt-5\"><b>Did you notice that the definition of an ‘internal rhyme’ <br /> is an internal rhyme?</b></div>"},
            new TextModel {FrameNumber = 108, Text = "<div class=\"display-2\"><b style=\"color:#0000FF;\">Internal rhyme</b></div> <div class=\"display-5 pt-5\"><b>Where...</b></div> <div class=\"display-5 pt-5\"><b>Two or more words <label class=\"text-success\">  rhyme</label> in the same <label class=\"text-success\">  line </label>.</b></div> <div class=\"display-5 pt-5\"><b>‘<label class=\"text-success\">Rhyme</label>’ and ‘<label class=\"text-success\">line</label>’ both rhyme with each other and they <br /> are in the same line.</b></div> <div class=\"display-5 pt-5\"><b>This is why the definition itself is an internal <br /> rhyme!</b> </div>"},
            new TextModel {FrameNumber = 124, Text = "<div class=\"display-2\"><b style=\"color:#0000FF;\">Repetition</b></div> <div class=\"display-5 pt-5 pb-5\"><b><label style=\"color:#0000FF;\">Repetition</label> is where a line or a word is repeated more than once! <br /> <label style=\"color:#0000FF;\">Repetition</label> is where a line or a word is repeated more than once! <br /><label style=\"color:#0000FF;\"> Repetition</label> is where a line or a word is repeated more than once!</b></div> <div class=\"display-5 pt-5 pb-5\"><b>Say the definition three times out loud.</b></div> <div class=\"display-5 pt-5\"><b>You have just used repetition. </b></div>"},
            new TextModelFrame136 { FrameNumber = 136, Text="<div class=\"row text-start\"><div class=\"col-10 offset-2   display-4 mb-5 animate__animated animate__fadeInUp animate__slower\"><b> You will have 90 seconds to identify the internal rhyme in<br>each part of the following rap!</b></div></div><div class=\"row text-start mt-5 mb-5 pt-5 pb-5 animate__animated animate__fadeInUp animate__slower animate__delay-3s \"><div class=\"col-4 offset-6 display-4\"><b>  Don’t worry…</b></div></div><div class=\"row text-start animate__animated animate__fadeInUp animate__slower animate__delay-5s  mt-5 pt-5\"><div class=\"col-10 offset-2 display-4\"> <b>   You won’t have to cover the whole rap at the same time,  <br> you will have four bars come up at a time.</b></div></div>"},
            new TextModel { FrameNumber = 146, Text = "Well done!"},
            new TextModelFrame136 { FrameNumber = 148, Text="<div class=\"row text-start\"><div class=\"col-4 offset-1  display-5 animate__animated animate__fadeInUp animate__slower z-130\"><b> You’re becoming a <br>master rapper...</b></div></div><div class=\"row text-start mt-5 \"><div class=\"col-2 offset-5 offset-5 display-5 animate__animated animate__fadeInUp animate__slower animate__delay-3s z-130\"><b>But...</b></div></div><div class=\"row text-start  mt-5\"><div class=\"col-5 offset-7  display-5 animate__animated animate__fadeInUp animate__slower animate__delay-5s z-130\"> <b>Did you know rappers<br>use similes in their <br> raps?</b></div></div>"},
            new TextModelFrame136{ FrameNumber = 149 , Header = "<b style=\"color:#0000FF;\" class=\" display-1\">Simile</b>", Text = "<div class=\"row text-center\"><div class=\"col-12 display-2  animate__animated animate__fadeInUp animate__slower\"><b>Similes are comparing two<br>things using the words ‘<b class=\"text-success\">like</b>’ or<br>  ‘<b class=\"text-success\">as</b>’</b></div></div><div class=\"row text-center mt-5\"><div class=\"col-12 display-2 animate__animated animate__fadeInUp animate__slower animate__delay-3s \"><b>When you see the word <br> ‘simile’ just think of the word <br> ‘similar’.</b></div></div><div class=\"row text-center mt-5\"><div class=\"col-12 display-2 animate__animated animate__fadeInUp animate__slower animate__delay-5s \"><b>Let’s go through some simile examples…​</b></div></div>" },
            new TextModelFrame136{ FrameNumber = 151 , Header = "<b style=\"color:#0000FF;\"  class=\" display-1 animate__animated animate__zoomIn animate__slower\">Overexaggerate </b>", Text = "<div class=\"row text-start\"><div class=\"mt-5 col-10 offset-2 display-4 animate__animated animate__fadeInUp animate__delay-2s animate__slower\"><b>To overexaggerate is to exaggerate, which</b><br><b>means to make something much bigger,<br>better or worse than it actually is.</b> </div></div><div class=\"row text-start    mt-5\"><div class=\"col-10 offset-2 display-4 animate__animated animate__fadeInUp animate__delay-4s animate__slower\"><b><b>For example: </b><label class=\"text-success\"> I’m so hungry I can eat an</label><br><label class=\"text-success\">elephant! </label>This is an over exaggeration<br>explaining how hungry I am. Could I<br>actually eat an elephant? No</b></div></div><div class=\"row text-center mt-5\"><div class=\"col-4 offset-8 display-4 animate__animated animate__fadeInUp animate__delay-6s animate__slower\"><b>Or could I….​</b></div></div>" },
            new TextModelFrame136{ FrameNumber = 152 , Header = "<b class=\" display-4 animate__animated animate__fadeInUp animate__slower\"><b>Remember</b></b>", Text = "<div class=\"row text-center\"><div class=\"col-12 display-5 animate__animated animate__fadeInUp animate__slower\"><b>Similes are easy to find! </b></div></div><div class=\"row text-center mt-5\"><div class=\"col-12 display-4 animate__animated animate__fadeInUp animate__slower\"><b>You need to remember that there are two words<br>that you should look for to identify a simile, those<br>words are…​</b></div></div><div class=\"row text-center mt-5 animate__animated animate__fadeInUp animate__slower animate__delay-2s\"><div class=\"col-12 display-1\"><b>Like​</b></div></div><div class=\"row text-center mt-5 animate__animated animate__fadeInUp animate__slower animate__delay-4s\"><div class=\"col-12 display-1\"><b>As​</b></div></div>" },
            new TextModelFrame136{ FrameNumber = 153 , Text = "<div class=\"row text-center animate__animated animate__fadeInUp animate__slower\"><div class=\"col-12 display-3\"><b>Have a look at the similes that are going<br>to appear.  </b></div></div><div class=\"row text-center mt-5 animate__animated animate__fadeInUp animate__slower\"><div class=\"col-12 display-3\"><b>Your task is to click on the word that<br>shows us that it is a simile!​​</b></div></div>"},
            new TextModel {FrameNumber = 162, Text = "Well done!​<br>You learnt what a simile is"},
            new TextModel { FrameNumber = 165, Text = "<div class=\"display-3 text-center\"><b>Let’s play a game to test your simile knowledge!</b></div>" },
            new TextModel{ FrameNumber = 166, Text = "<div class=\"display-5 text-center\"><b>5 images are going to appear on the screen</b></div> <div class=\"display-5 text-center pt-5\"><b>You will see one half of the simile</b></div> <div class=\"display-5 text-center pt-5\"><b>You need to drag and drop the other part of <br> the simile to make the whole simile make <br> sense </b></div>"},
            new TextModel{ FrameNumber = 183, Text="<div class=\"display-2 text-center\"><b>Challenge time!</b></div> <div class=\"display-2 text-center pt-5\"><b>This challenge will win you three Mystic <br> Mics</b></div>"},
            new TextModel{ FrameNumber = 187, Text="<div class=\"display-4 text-center\"><b>This is the section where you become <br> a superstar rapper!</b></div>"},
            new TextModel{ FrameNumber = 188, Text="<div class=\"display-4 text-center\"><b>Your task will be to write about <br> the emotions that appear using <br> a specific rhyme scheme</b></div>" },
            new TextModel{ FrameNumber = 204, Text="<div class=\"display-3\"><b>Let’s see if you can <br> continue the challenge <br> writing raps without the <br> words being coloured!</b></div>"},
            new TextModel{FrameNumber = 267, Text="<div class=\"display-3\"><b>I would like you to write one more <br> rap and after you write this rap, <br> make sure you wait for the next <br> page so you can download your <br> certificate and see what I suggest <br> you write about in your own time!</b></div>"},
            new TextModel{FrameNumber = 232, Text="<div class=\"display-2\" style=\"padding-top:5rem;\"><b>Did you call for my help?</b></div> <div class=\"display-2 text-center\" style=\"padding-top:15rem;\"><b>Let me explain to you how the <br> rap battle will work and then we <br> can do some practice.</b></div>"},
            new TextModel{FrameNumber = 233, Text="<div class=\"display-3\" style=\"padding-top:5rem;\"><b>Don’t you worry…</b></div> <div class=\"display-3 text-center\" style=\"padding-top:10rem;\"><b>I’ve been in plenty of rap battles <br> and they’re very intense.</b></div> <div class=\"display-3\" style=\"padding-top:10rem; padding-left:45rem;\"><b>Here is what you <br> have to do…</b></div>"},
            new TextModel{FrameNumber = 234, Text="<div class=\"display-3 text-center mt-5\" ><b>There will be a timer on the <br> screen that looks like this</b></div> <div id=\"app\" class=\"text-center mt-5 col-4 offset-4\"></div> <div class=\"display-3 text-center mt-5\" ><b>You need to pay <br> attention to the <br> timer!</b></div>"},
            new TextModel{FrameNumber = 235, Text="<div class=\"display-2\" style=\"padding-top:5rem;\"><b>When Mic Menace says a line, you <br> must type a line that rhymes with <br> his line, but don’t worry, I will give <br> you some words to help.</b></div> <div class=\"display-2\" style=\"padding-top:10rem;\"><b>You will have 20 seconds to write <br> your line otherwise you will lose <br> and will have to restart!</b></div>"},
            new TextModel{FrameNumber = 236, Text="<div class=\"display-1\" style=\"padding-top:20rem;\"><b>Let’s give it a shot…</b></div>"},
            new TextModel{FrameNumber = 242 , Text="<div class=\"display-3\" style=\"padding-top:5rem;\"><b>Wow, you’re pretty good at <br> battling…</b></div> <div class=\"display-3\" style=\"padding-top:5rem;\"><b>I think you’re ready to take on Mic <br> Menace!</b></div> <div class=\"display-3\" style=\"padding-top:5rem;\"><b>But before I go, I think you deserve <br> to have this…</b></div>"},
            new TextModel{FrameNumber = 226, Text="<div class=\"display-2\" style=\"padding-top:10rem;\"><b>HA HA HA</b></div> <div class=\"display-2\" style=\"padding-top:10rem; padding-left:20rem;\"><b>You don’t deserve <br> these Mystic Mics! Let <br> me take some of <br> them off of your <br> hands…</b></div>"},
            new TextModel{FrameNumber = 229, Text="<div class=\"display-3\" style=\"padding-top:9rem; padding-left:5rem;\"><b>The only way <br> you can get <br> these back is if <br> you beat me in a <br> rap battle…</b></div> <div class=\"display-3\" style=\"padding-top:10rem; padding-left:30rem;\"><b>And no one has <br> ever beaten me!</b></div>"},
            new TextModel{FrameNumber = 247, Text="<div class=\"display-3\" style=\"padding-top:10rem; padding-left:5rem;\"><b>Ha…</b></div> <div class=\"display-3\" style=\"padding-top:9rem; padding-left:15rem;\"><b>I see Rapping Rabbit has <br> done some practice with <br> you – but I am much <br> harder, and you have to <br> beat me if you want to get <br> these microphones back!</b></div>"},
            new TextModel{FrameNumber = 248, Text="<div class=\"display-1 text-center\" style=\"padding-top:15rem;\"><b>Before we start, <br> I just want to <br> make a few <br> adjustments….</b></div>"},
            new TextModel{FrameNumber = 249, Text="<div class=\"display-1\" style=\"padding-top:15rem; padding-left:15rem;\"><b>Let me make some <br> adjustments to the <br> timer!</b></div>"},
            new TextModel{FrameNumber = 262, Text="<div class=\"display-1\" style=\"padding-top:5rem; padding-left:5rem;\"><b>Oh no…</b></div> <div class=\"display-1\" style=\"padding-top:10rem; padding-left:25rem;\"><b>You were able to <br> beat me…</b></div> <div class=\"display-1\" style=\"padding-top:10rem; padding-left:60rem;\"><b>Ah!</b></div>"},
            new TextModel{FrameNumber = 263, Text="<div class=\"display-3\" style=\"padding-top:5rem; padding-left:5rem;\"><b>I guess a deal is a <br> deal</b></div> <div class=\"display-3\" style=\"padding-top:2rem; padding-left:20rem;\"><b>Here are your <br> Mystic Mics back</b></div> <div class=\"display-3\" style=\"padding-top:5rem; padding-left:50rem;\"><b>I will get you <br> next time!</b></div>"}
        };


        public static TextModel GetTextForframe(int frameNumber)
        {
            return TextsForFrames.Find(x => x.FrameNumber == frameNumber);
        }

        public static bool IfTemplateExists(int frameNumber)
        {
            var result = TextsForFrames.Find(x => x.FrameNumber == frameNumber);

            if (result == null)
            {
                return false;
            }
            else
            {
                return true;
            }
        }
    }
}
